/*
--------------------------------------------------------------------------------

	Shaders Shaders

	Copyright (C) 2024 None
	Apache License 2.0

    Pass: Motion Blur

--------------------------------------------------------------------------------
*/

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const vec2 workGroupsRender = vec2(1.0, 1.0);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

restrict writeonly uniform image2D colorimg0; // Motion blur output

#include "/lib/universal/Uniform.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Random.glsl"

vec3 MotionBlur(in ivec2 texel) {
	vec2 motionVector = texelFetch(colortex3, texel, 0).xy;
	float motionNorm = inversesqrt(sdot(motionVector));

	if (motionNorm > 1e6) return texelFetch(colortex1, texel, 0).rgb;
	motionVector *= saturate(motionNorm);

	const float strength = MOTION_BLUR_STRENGTH / float(MOTION_BLUR_SAMPLES) * 0.01;
	motionVector *= strength / max(frameTime, 1e-3) * viewSize;

	float dither = BlueNoiseTemporal(texel);

    vec2 sampleCoord = vec2(texel) + 0.5 + motionVector * dither;
	sampleCoord -= motionVector * MOTION_BLUR_SAMPLES * 0.5;

	vec3 sum = vec3(0.0);
	float sumWeight = 0.0;

	for (uint i = 0u; i < MOTION_BLUR_SAMPLES; ++i, sampleCoord += motionVector) {
		if (clamp(sampleCoord, vec2(0.0), viewSize - 1.0) == sampleCoord) {
			sum += texelFetch(colortex1, ivec2(sampleCoord), 0).rgb;
			++sumWeight;
		}
	}

	if (sumWeight < EPS) return texelFetch(colortex1, texel, 0).rgb;

	return sum * rcp(sumWeight);
}

//======// Main //================================================================================//
void main() {
	ivec2 screenTexel = ivec2(gl_GlobalInvocationID.xy);

    imageStore(colorimg0, screenTexel, vec4(MotionBlur(screenTexel), 1.0));
}