/*
--------------------------------------------------------------------------------

	Shaders Shaders

	Copyright (C) 2024 None
	Apache License 2.0

--------------------------------------------------------------------------------
*/

#define PASS_CLOUD_SM

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(32, 32, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly uniform image2D cloudShadowImg;

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Random.glsl"

#include "/lib/atmosphere/Common.glsl"
#include "/lib/atmosphere/clouds/Shadows.glsl"

//======// Main //================================================================================//
void main() {
	ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
	bool historyReset = viewSizeChanged || worldTimeChanged;

    // Checkerboard render cloud shadow map
	ivec2 offset = checkerboardOffset4x4[frameCounter % 16];
	if (gid % 4 == offset || historyReset) {
		vec2 uv = (vec2(gid) + 0.5) * rcp(textureSize(cloudShadowTex, 0));
        vec3 rayPos = SetupCloudShadowPos(uv);
        float cloudShadow = CalculateCloudShadows(rayPos);

		// Accumulate
		float accumFactor = historyReset ? 1.0 : 0.125;
		float cloudShadowPrev = texelFetch(cloudShadowTex, gid, 0).x;
		cloudShadow = mix(cloudShadowPrev, cloudShadow, accumFactor);

		imageStore(cloudShadowImg, gid, vec4(cloudShadow));
	}
}