/*
--------------------------------------------------------------------------------

	Shaders Shaders

	Copyright (C) 2024 None
	Apache License 2.0

--------------------------------------------------------------------------------
*/

#define PASS_SKY_MAP

//======// Input //===============================================================================//

layout (local_size_x = 16, local_size_y = 16) in;
const ivec3 workGroups = ivec3(16, 16, 1);

//======// Utility //=============================================================================//

#include "/lib/Utility.glsl"

//======// Uniform //=============================================================================//

writeonly uniform image2D skyMapImg;

#include "/lib/universal/Uniform.glsl"

//======// SSBO //================================================================================//

#include "/lib/universal/SSBO.glsl"

//======// Function //============================================================================//

#include "/lib/universal/Random.glsl"

#include "/lib/atmosphere/Common.glsl"
#include "/lib/atmosphere/Bruneton08.glsl"

#include "/lib/atmosphere/clouds/Render.glsl"
#include "/lib/atmosphere/AtmosphericFog.glsl"

//======// Main //================================================================================//
void main() {
	ivec2 gid = ivec2(gl_GlobalInvocationID.xy);
	bool historyReset = viewSizeChanged || worldTimeChanged;

    // Checkerboard render
	ivec2 offset = checkerboardOffset2x2[frameCounter % 4];
	if (gid % 2 == offset || historyReset) {
		vec2 uv = (vec2(gid) + 0.5) * rcp(skyMapRes);

		vec3 worldDir = UnprojectSky(uv);
		vec3 skyRadiance = GetSkyRadiance(worldDir, worldSunVector) * SKY_SPECTRAL_RADIANCE_TO_LUMINANCE;

		vec2 noise = SampleStbnVec2(gid, frameCounter);

		#ifdef CLOUDS
			float cloudDepth;
			vec4 cloudData = RenderClouds(worldDir, noise, cloudDepth);
			skyRadiance = skyRadiance * cloudData.a + cloudData.rgb;
		#endif

		#ifdef VOLUMETRIC_FOG
			if (isEyeInWater == 0) {
				mat2x3 volFogData = RaymarchAtmosphericFog(worldDir * far, noise.x, true);
				skyRadiance = ApplyFog(skyRadiance, volFogData);
			}
		#endif

		// Accumulate
		vec4 history = texelFetch(skyMapTex, gid, 0);
		history.a *= float(!historyReset);

		skyRadiance = mix(history.rgb, skyRadiance, rcp(++history.a));
		imageStore(skyMapImg, gid, vec4(skyRadiance, min(history.a, 128.0)));
	}
}